### ISSUE TITLE
no output even with -debug option

### ISSUE THREAD

**Issue by imageslr** [ofabry/go-callvis#102]
I run below command in my repo:

```
 go-callvis -focus ./ -limit ./ -nostd -debug ./
```

But there were no output. I've already built this repo. Is this because that the repo is too large?

go-callvis has the highest cpu usage:
 
![image](https://user-images.githubusercontent.com/17822028/135055329-a84f1a95-a777-44dc-93cf-a88e331d897d.png)

**Comment by ofabry** [comment]
How long does it run like this? Does it ever finish? Try setting `-focus=main`.

**Comment by imageslr** [comment]
The environment on my machine has been reset. I cannot reproduce it. Thanks for your reply.
