### ISSUE TITLE
Unable to generate executable file

### ISSUE THREAD

**Issue by 1511563371** [ofabry/go-callvis#123]
```
runtime environmet:
win10 + go1.8.1
```

```
step :
1  go mod init XXX
2 >go get -u github.com/ofabry/go-callvis@latest

result :
$GOPATH/bin : no  executable file

```

**Comment by ofabry** [comment]
The error message you posted is most likely not coming from the go-callvis, but your system / go environment.

Are you really using go **v1.8.1**? That is a VERY OLD version, not officially supported anymore. 
The last stable release of go is  **v1.19** and the [**Requirements**](https://github.com/ofabry/go-callvis/blob/master/README.md#requirements) section in the README specifies go **v1.17** as the **minimum Go version supported by go-callvis**.
