### ISSUE TITLE
build error  cannot load github.com/goccy/go-graphviz/internal/ccall: no Go source files

### ISSUE THREAD

**Issue by huanghuangzym** [ofabry/go-callvis#80]
make install
build github.com/goccy/go-graphviz/internal/ccall: cannot load github.com/goccy/go-graphviz/internal/ccall: no Go source files
build github.com/goccy/go-graphviz/internal/ccall: cannot load github.com/goccy/go-graphviz/internal/ccall: no Go source files
go install -tags "" -ldflags "-X main.commit=v0.6.1"
build github.com/goccy/go-graphviz/internal/ccall: cannot load github.com/goccy/go-graphviz/internal/ccall: no Go source files
Makefile:22: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by CedrusZhao** [comment]
I alse meet this.

**Comment by ofabry** [comment]
Please provide the following information:

- Operating system
- Output of `go env`
- Exact command/flags used, `go-callvis ...`

**Comment by huanghuangzym** [comment]
thanks ,i resolve it ,export CGO_ENABLED=0 then compile success ,thanks
