### ISSUE TITLE
Generate call graph for packages that depends on Go 1.16

### ISSUE THREAD

**Issue by suntong** [ofabry/go-callvis#99]
Hi,

- My Go is `go-1.15`, and
- I downloaded `github.com/xo/xo` which needs Go 1.16 to compile and
- I want to use `go-callvis` to generate call graph for it, but 

This is what I got:

```
$ go-callvis -ignore embed,io/fs .
templates/templates.go:6:2: cannot find package "embed" in any of:
        /usr/lib/go-1.15/src/embed (from $GOROOT)
        /path/to/Go/src/embed (from $GOPATH)
templates/templates.go:8:2: cannot find package "io/fs" in any of:
        /usr/lib/go-1.15/src/io/fs (from $GOROOT)
        /path/to/Go/src/io/fs (from $GOPATH)
/path/to/Go/src/github.com/xo/xo/templates/templates.go:6:2: could not import embed (invalid package name: "")
/path/to/Go/src/github.com/xo/xo/templates/templates.go:8:2: could not import io/fs (invalid package name: "")
/path/to/Go/src/github.com/xo/xo/cmd/cmd.go:231:53: DirFS not declared by package os
. . .
```

I've already use `-ignore embed,io/fs` to tell `go-callvis` to ignore `embed,io/fs`, but why it is still trying to work on it?

Internally, how does thing work? E.g, if I got one `go-callvis`  compiled with `go-1.16`, would it understand packages that depends on Go 1.16, while my go is still 1.15? 

thanks

**Comment by ofabry** [comment]
The call graph analysis happens for the source code and since it uses some internal Go libraries it will use the ones installed to resolve the call graph. The project you ran it for requires go 1.16 so to build the call graph you will need go 1.16 too.

**Comment by suntong** [comment]
OK, Thanks. So

- I might not need `go-callvis` to be compiled with `go-1.16`, but
- I need `go-1.16` environment to generate call graph for packages that needs Go 1.16,

right?

**Comment by ofabry** [comment]
Yes, that is correct.

**Comment by suntong** [comment]
Thanks! will do.
